# Dependencies
markdown: kramdown
highlighter: rouge

include: ["_pages"]
permalink: /:title/
future: true

# Setup
title: "viva la dataviz"
tagline: "Portfolio & Blog"
description: "A joint project by Courtney and Sergio"
url: "https://vivaladataviz.com"
baseurl: "/"
logo: "assets/favicon/favicon-32x32.png"

author:
  name: "Courtney and Sergio"
  url: https://twitter.com/VivaLaDataviz
  email: vivaladataviz@gmail.com
  twitter_user: vivaladataviz

paginate: 5

# Plugins
whitelist: []
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Custom vars
version: 2.1.0

github:
  username: vivaladataviz
  repo: vivaladataviz.github.io

sass_dir: /assets/_sass

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    _posts/2020-04-25-template.md,
    README.md,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
